name: Test CD

on:
  push:
    branches: [ main ]

env:
  SERVER_HOST: 91.200.151.163
  SERVER_USERNAME: root
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_PASSWORD }}


jobs: 
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SSH_PRIVATE_KEY }}
        # key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/amo_crm_admin/
          git pull
          npm install
          ng build
          sudo rsync -av --delete /root/amo_crm_admin/dist/amo_crm_admin/ /var/www/amo_crm_admin/